@host = localhost
@port = 8080
@api_version_v1 = v1
@authenticationEndpoint = authentications

### GET /health-check
GET http://{{host}}:{{port}}/health-check
Accept-Language: en_US

### POST /authentications/sign-up
POST http://{{host}}:{{port}}/{{api_version_v1}}/{{authenticationEndpoint}}/sign-up
Content-Type: application/json
Accept-Language: en_US

{
    "data":
    {
        "username":1111,
        "password":"Parnupong1992"
    }
}

### GET /authentications/sign-out
GET http://{{host}}:{{port}}/{{api_version_v1}}/{{authenticationEndpoint}}/sign-out
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk1MTkxMjh9.Jn65tM8FbTUX96cre07PU-mQJmztnnDtOcaYZfywhp8
Accept-Language: en_US