app:
    port: 8080
    env: DEV # PRD, DEV

db:
    driver: mysql
    host: localhost
    port: 3306
    database: templatego
    username: root
    password: P@ssw0rd

api:
    email: "http://localhost:8002/v2/email/rename-service-name-here"

cryption:
    privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAt0tBZGhBAE+NXng2eMi04bSSiJdf9/7dhrlgByIMNQO2bZZg
        03whnr5YnQnAs137NshSrETleNmcsox5QUNTTOKGvSqaRr7lQRtEUESoL12B6grm
        I+flSq5W4rVrG+jusNU+wz71zso/skoLGXPn1wYH7HSBhetstOLeGOCW5kyRA32/
        8iLcJ3NeUi/nMqBeEvXstIGDTI2mNHFg/8jJwAz/3/bzWILYnUnFig/53l7Isb8G
        b/qWYJPB0SVvmoZAcybd9BQCcTGFY+c8tbS5OKhHNNVDsPox0Z/kLwmgBTlJIeAn
        etsIS8EORLhl2AmKIwbAfkff5YF8y8m2qHJ+pwIDAQABAoIBAQCFp05rlMmxHFEN
        TcMKl++tlSo0h4znHOUT1CB9kworriVcC4dXLvCk/E9JU088e48vByuhiit5z9Q/
        LcdNG3amXZe6YFJWu+QXcXaCwU2SHDEbJA9kpze/GRkp/ve3RkamkxhM7p/2xetk
        ajFlweqQFEm61cmMiXqe+77PjRT7oCMtJH4krAlPKZkSEnG2ispPbmcRNClBG8ey
        QIgBiU3v0XEhdgf5NTsb1re4Q3f/4Mf1feTrn3TvclAeblih3Ce0w8Mg+T4Cm6i0
        wHjtp29J9CBKW5vVs4amNItdsI9Ul5jKjd/Ni2xvftuff5AMgL859qUdm9dNaXLq
        z9SumtXBAoGBAMEToKriA1husjPU4TD9gkYbcz1niZcKWYpoNf26bHoDh5T/CFB+
        DWwhqTag1hbfNxXdh9q/dbU9EmilpplDwg4LGu/7HKlvBk2eCzj+OaHPdryZqSEt
        PACoUkqtmgqa6cov4Zu9scrxmi1h8sr+inmXhzYj/uXfWAkkc/MjigXZAoGBAPMH
        dSOVvHw56CRn3FSTjEWNvPoWHfHCQGdn/Z7Jagc316yln8CJASdktf0T5MCATBsF
        Yf4EtSHbZ3c1O2MTplbfNd1cpatxVAU422fRG1MlCMX9vdrPQi+84cQBub2LL9Fj
        e+iGcC1UbzPdHoiMvLFj46goWk6X9C4Y2H+fT1h/AoGAEycESA81b79DVBro37g2
        BQhSDSRJJL91FGK0AGBOxGe3OlN2Gq32XOSV6YJY2ln4F+YqxMs7POg6/EB6Xze2
        dzgoyudo93G4+VgVGuk1BFUVHS5M9aqMCjCoQRopbqXhTRok0hMmINCIj7nooLRR
        PjCGzBsT/O+DxxxjmBnNZjkCgYABDo4+2l7Yd3P//IejwoSApO4mdEQrEfovuO8M
        arnQUDja4lmAf9gGcNStxhFfmO87ytkzPpf/DrIzfYLFmodFp3DXhpid1z9TSn0B
        xZIF2YphOgpCUlZqWLrunEdPgLRzh6g5SaRhPhXBtvt0ApCrgNCzoYFLCDQioy8F
        1w6ERwKBgAzVr2D+PSaRDPJhifbqtHNzR/IvWvsDQaBD4P1EYA7am5A00i0PLcH0
        rZI1H0k1sN+CLuIoAy9RG1et2ScSJ8fMTFh8M6iZS7Z8glJkbCvhdI9IWvClgUXk
        n25RprPzun4hbvb3lgqPMZKvUfRebhRb8nbCXHmyZdmXkIGKyUrt
        -----END RSA PRIVATE KEY-----
    publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0tBZGhBAE+NXng2eMi0
        4bSSiJdf9/7dhrlgByIMNQO2bZZg03whnr5YnQnAs137NshSrETleNmcsox5QUNT
        TOKGvSqaRr7lQRtEUESoL12B6grmI+flSq5W4rVrG+jusNU+wz71zso/skoLGXPn
        1wYH7HSBhetstOLeGOCW5kyRA32/8iLcJ3NeUi/nMqBeEvXstIGDTI2mNHFg/8jJ
        wAz/3/bzWILYnUnFig/53l7Isb8Gb/qWYJPB0SVvmoZAcybd9BQCcTGFY+c8tbS5
        OKhHNNVDsPox0Z/kLwmgBTlJIeAnetsIS8EORLhl2AmKIwbAfkff5YF8y8m2qHJ+
        pwIDAQAB
        -----END PUBLIC KEY-----

swagger:
    basePath: ""
